install.packages("dplyr")
library(dplyr)
help(package = dplyr)

read.csv("shrub-volume-experiment.csv")
shrub <- read.csv("shrub-volume-experiment.csv")
names(shrub)
str(shrub)
print(head(shrub))
print(shrub$length)
print(select(shrub, site, experiment))
filter(shrub, height > 5)
print(filter(shrub, height > 5))
mutate(shrub, "volume" = length * height * width)
shrub_data_w_vols <- mutate(shrub, "volume" = length * height * width)
print(shrub_data_w_vols)
